package Visualiza.FrenteDeCaixa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.JXImagePanel;
import Controle.Geral.ControleMonetário;


/**
 *
 * @author felipe
 */
public class FrenteDeCaixaCompleta extends javax.swing.JDialog {

     
    public String aux, ValorPago,trocado;
    public FormaPagamentoDialog formaPagamentoDialog;

    
    
    
    /**
     * Creates new form FormaPagamento1
     */
    public FrenteDeCaixaCompleta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
         Toolkit toolkit = Toolkit.getDefaultToolkit();    
         Dimension scrnsize = toolkit.getScreenSize();  
         setSize(scrnsize.width, scrnsize.height);
       
        setLocationRelativeTo(null);
       
        PainelValorPago.setOpaque(false);
        Opercao.setOpaque(false);
        DescricaoProduto.setOpaque(false);
        InformacaoSistema.setOpaque(false);
        ValortotalCompra.setOpaque(false);
        imagePanelLogo.setOpaque(false);
        ValorTotalApagar.setOpaque(false);
        
        
        SubTotal.requestFocus();
        
        Desconto.setDocument(new ControleMonetário());
        SubTotal.setDocument(new ControleMonetário());
        
        
        ImageIcon imagemLogo = new ImageIcon(getClass().getResource("/Img/LogoPrincipais/LogoCliente.png"));        
        imagePanelLogo.setImage(imagemLogo.getImage());
        imagePanelLogo.setStyle(JXImagePanel.Style.SCALED);  
        
        
        
        ImageIcon imagem = new ImageIcon(getClass().getResource("/Img/Graficos/FundosCaixa.png"));        
        imagePanel.setImage(imagem.getImage());
        imagePanel.setStyle(JXImagePanel.Style.SCALED);  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new org.jdesktop.swingx.JXImagePanel();
        jLabel20 = new javax.swing.JLabel();
        SubTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Desconto = new javax.swing.JTextField();
        PainelValorPago = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        Opercao = new javax.swing.JPanel();
        FinalizarCompra = new javax.swing.JButton();
        FinalizarCompra1 = new javax.swing.JButton();
        FinalizarCompra2 = new javax.swing.JButton();
        FinalizarCompra3 = new javax.swing.JButton();
        FinalizarCompra4 = new javax.swing.JButton();
        FinalizarCompra5 = new javax.swing.JButton();
        FinalizarCompra6 = new javax.swing.JButton();
        FinalizarCompra7 = new javax.swing.JButton();
        FinalizarCompra8 = new javax.swing.JButton();
        FinalizarCompra9 = new javax.swing.JButton();
        FinalizarCompra10 = new javax.swing.JButton();
        FinalizarCompra11 = new javax.swing.JButton();
        DescricaoProduto = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        InformacaoSistema = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Desconto1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Desconto2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Desconto3 = new javax.swing.JTextField();
        ValortotalCompra = new javax.swing.JPanel();
        imagePanelLogo = new org.jdesktop.swingx.JXImagePanel();
        ValorTotalApagar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        imagePanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imagePanelKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Codigo ou descrição de item");

        SubTotal.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        SubTotal.setText("0.00");
        SubTotal.setToolTipText("");
        SubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTotalActionPerformed(evt);
            }
        });
        SubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SubTotalKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Quantidade");

        Desconto.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        Desconto.setText("0.00");
        Desconto.setToolTipText("");
        Desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescontoActionPerformed(evt);
            }
        });
        Desconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DescontoKeyPressed(evt);
            }
        });

        PainelValorPago.setBackground(new java.awt.Color(255, 255, 255));
        PainelValorPago.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout PainelValorPagoLayout = new javax.swing.GroupLayout(PainelValorPago);
        PainelValorPago.setLayout(PainelValorPagoLayout);
        PainelValorPagoLayout.setHorizontalGroup(
            PainelValorPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        PainelValorPagoLayout.setVerticalGroup(
            PainelValorPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jButton2.setBackground(new java.awt.Color(252, 0, 50));
        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botao/delete.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Opercao.setBackground(new java.awt.Color(255, 255, 255));
        Opercao.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        FinalizarCompra.setText("Finalizar venda F1");
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });
        FinalizarCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompraKeyPressed(evt);
            }
        });

        FinalizarCompra1.setText("Finalizar venda F1");
        FinalizarCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra1ActionPerformed(evt);
            }
        });
        FinalizarCompra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra1KeyPressed(evt);
            }
        });

        FinalizarCompra2.setText("Forma pagamento F2");
        FinalizarCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra2ActionPerformed(evt);
            }
        });
        FinalizarCompra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra2KeyPressed(evt);
            }
        });

        FinalizarCompra3.setText("Finalizar venda F1");
        FinalizarCompra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra3ActionPerformed(evt);
            }
        });
        FinalizarCompra3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra3KeyPressed(evt);
            }
        });

        FinalizarCompra4.setText("Localizar produto F3");
        FinalizarCompra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra4ActionPerformed(evt);
            }
        });
        FinalizarCompra4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra4KeyPressed(evt);
            }
        });

        FinalizarCompra5.setText("Finalizar venda F1");
        FinalizarCompra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra5ActionPerformed(evt);
            }
        });
        FinalizarCompra5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra5KeyPressed(evt);
            }
        });

        FinalizarCompra6.setText("Finalizar venda F1");
        FinalizarCompra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra6ActionPerformed(evt);
            }
        });
        FinalizarCompra6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra6KeyPressed(evt);
            }
        });

        FinalizarCompra7.setText("Finalizar venda F1");
        FinalizarCompra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra7ActionPerformed(evt);
            }
        });
        FinalizarCompra7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra7KeyPressed(evt);
            }
        });

        FinalizarCompra8.setText("Finalizar venda F1");
        FinalizarCompra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra8ActionPerformed(evt);
            }
        });
        FinalizarCompra8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra8KeyPressed(evt);
            }
        });

        FinalizarCompra9.setText("Finalizar venda F1");
        FinalizarCompra9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra9ActionPerformed(evt);
            }
        });
        FinalizarCompra9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra9KeyPressed(evt);
            }
        });

        FinalizarCompra10.setText("Finalizar venda F1");
        FinalizarCompra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra10ActionPerformed(evt);
            }
        });
        FinalizarCompra10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra10KeyPressed(evt);
            }
        });

        FinalizarCompra11.setText("Finalizar venda F1");
        FinalizarCompra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra11ActionPerformed(evt);
            }
        });
        FinalizarCompra11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarCompra11KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout OpercaoLayout = new javax.swing.GroupLayout(Opercao);
        Opercao.setLayout(OpercaoLayout);
        OpercaoLayout.setHorizontalGroup(
            OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpercaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinalizarCompra)
                    .addComponent(FinalizarCompra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinalizarCompra3)
                    .addComponent(FinalizarCompra2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FinalizarCompra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FinalizarCompra5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinalizarCompra6)
                    .addComponent(FinalizarCompra7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinalizarCompra8)
                    .addComponent(FinalizarCompra9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinalizarCompra10)
                    .addComponent(FinalizarCompra11))
                .addGap(137, 137, 137))
        );
        OpercaoLayout.setVerticalGroup(
            OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpercaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OpercaoLayout.createSequentialGroup()
                        .addComponent(FinalizarCompra10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalizarCompra11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OpercaoLayout.createSequentialGroup()
                        .addComponent(FinalizarCompra8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalizarCompra9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OpercaoLayout.createSequentialGroup()
                        .addComponent(FinalizarCompra6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalizarCompra7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(OpercaoLayout.createSequentialGroup()
                            .addComponent(FinalizarCompra4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FinalizarCompra5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(OpercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OpercaoLayout.createSequentialGroup()
                                .addComponent(FinalizarCompra2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FinalizarCompra3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OpercaoLayout.createSequentialGroup()
                                .addComponent(FinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FinalizarCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DescricaoProduto.setBackground(new java.awt.Color(255, 255, 255));
        DescricaoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("cola em lada 200 ml");

        javax.swing.GroupLayout DescricaoProdutoLayout = new javax.swing.GroupLayout(DescricaoProduto);
        DescricaoProduto.setLayout(DescricaoProdutoLayout);
        DescricaoProdutoLayout.setHorizontalGroup(
            DescricaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescricaoProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DescricaoProdutoLayout.setVerticalGroup(
            DescricaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescricaoProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InformacaoSistema.setBackground(new java.awt.Color(255, 255, 255));
        InformacaoSistema.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("12:12:12");

        jLabel27.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Versão sistema");

        jLabel28.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Operador:");

        jLabel29.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("12/12/1212");

        javax.swing.GroupLayout InformacaoSistemaLayout = new javax.swing.GroupLayout(InformacaoSistema);
        InformacaoSistema.setLayout(InformacaoSistemaLayout);
        InformacaoSistemaLayout.setHorizontalGroup(
            InformacaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacaoSistemaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(InformacaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InformacaoSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InformacaoSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        InformacaoSistemaLayout.setVerticalGroup(
            InformacaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacaoSistemaLayout.createSequentialGroup()
                .addGroup(InformacaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacaoSistemaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InformacaoSistemaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(InformacaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addContainerGap())
        );

        Desconto1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        Desconto1.setText("0.00");
        Desconto1.setToolTipText("");
        Desconto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desconto1ActionPerformed(evt);
            }
        });
        Desconto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Desconto1KeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Valor unitário");

        jLabel24.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Desconto");

        Desconto2.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        Desconto2.setText("0.00");
        Desconto2.setToolTipText("");
        Desconto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desconto2ActionPerformed(evt);
            }
        });
        Desconto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Desconto2KeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Subtotal");

        Desconto3.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        Desconto3.setText("0.00");
        Desconto3.setToolTipText("");
        Desconto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desconto3ActionPerformed(evt);
            }
        });
        Desconto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Desconto3KeyPressed(evt);
            }
        });

        ValortotalCompra.setBackground(new java.awt.Color(255, 255, 255));
        ValortotalCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout ValortotalCompraLayout = new javax.swing.GroupLayout(ValortotalCompra);
        ValortotalCompra.setLayout(ValortotalCompraLayout);
        ValortotalCompraLayout.setHorizontalGroup(
            ValortotalCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ValortotalCompraLayout.setVerticalGroup(
            ValortotalCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        imagePanelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout imagePanelLogoLayout = new javax.swing.GroupLayout(imagePanelLogo);
        imagePanelLogo.setLayout(imagePanelLogoLayout);
        imagePanelLogoLayout.setHorizontalGroup(
            imagePanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanelLogoLayout.setVerticalGroup(
            imagePanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ValorTotalApagar.setBackground(new java.awt.Color(255, 255, 255));
        ValorTotalApagar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout ValorTotalApagarLayout = new javax.swing.GroupLayout(ValorTotalApagar);
        ValorTotalApagar.setLayout(ValorTotalApagarLayout);
        ValorTotalApagarLayout.setHorizontalGroup(
            ValorTotalApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ValorTotalApagarLayout.setVerticalGroup(
            ValorTotalApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DescricaoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Opercao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePanelLayout.createSequentialGroup()
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PainelValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ValortotalCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Desconto3)
                                    .addComponent(Desconto2)
                                    .addComponent(Desconto1)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ValorTotalApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagePanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InformacaoSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanelLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(SubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(DescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(6, 6, 6)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(PainelValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ValortotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(6, 6, 6)
                        .addComponent(Desconto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desconto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desconto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ValorTotalApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Opercao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformacaoSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTotalActionPerformed

    private void SubTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubTotalKeyPressed

        if(evt.getKeyCode() == evt.VK_ENTER){

            Desconto.requestFocus();
            // botao.requestFocus();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SubTotalKeyPressed

    private void DescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescontoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_DescontoActionPerformed

    private void DescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescontoKeyPressed

        if(evt.getKeyCode() == evt.VK_ENTER){

         
            // botao.requestFocus();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_DescontoKeyPressed

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    private void FinalizarCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompraKeyPressed

        if(evt.getKeyCode() == evt.VK_ENTER){

            dispose();
            // botao.requestFocus();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompraKeyPressed

    private void imagePanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imagePanelKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_imagePanelKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Desconto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desconto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desconto1ActionPerformed

    private void Desconto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Desconto1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desconto1KeyPressed

    private void Desconto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desconto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desconto2ActionPerformed

    private void Desconto2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Desconto2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desconto2KeyPressed

    private void Desconto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desconto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desconto3ActionPerformed

    private void Desconto3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Desconto3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desconto3KeyPressed

    private void FinalizarCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra1ActionPerformed

    private void FinalizarCompra1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra1KeyPressed

    private void FinalizarCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra2ActionPerformed
       formaPagamentoDialog = new FormaPagamentoDialog(null, rootPaneCheckingEnabled);
       formaPagamentoDialog.setVisible(true);
        
        
    // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra2ActionPerformed

    private void FinalizarCompra2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra2KeyPressed

    private void FinalizarCompra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra3ActionPerformed

    private void FinalizarCompra3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra3KeyPressed

    private void FinalizarCompra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra4ActionPerformed

    private void FinalizarCompra4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra4KeyPressed

    private void FinalizarCompra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra5ActionPerformed

    private void FinalizarCompra5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra5KeyPressed

    private void FinalizarCompra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra6ActionPerformed

    private void FinalizarCompra6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra6KeyPressed

    private void FinalizarCompra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra7ActionPerformed

    private void FinalizarCompra7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra7KeyPressed

    private void FinalizarCompra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra8ActionPerformed

    private void FinalizarCompra8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra8KeyPressed

    private void FinalizarCompra9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra9ActionPerformed

    private void FinalizarCompra9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra9KeyPressed

    private void FinalizarCompra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra10ActionPerformed

    private void FinalizarCompra10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra10KeyPressed

    private void FinalizarCompra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra11ActionPerformed

    private void FinalizarCompra11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarCompra11KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra11KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrenteDeCaixaCompleta dialog = new FrenteDeCaixaCompleta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Desconto;
    private javax.swing.JTextField Desconto1;
    private javax.swing.JTextField Desconto2;
    private javax.swing.JTextField Desconto3;
    private javax.swing.JPanel DescricaoProduto;
    private javax.swing.JButton FinalizarCompra;
    private javax.swing.JButton FinalizarCompra1;
    private javax.swing.JButton FinalizarCompra10;
    private javax.swing.JButton FinalizarCompra11;
    private javax.swing.JButton FinalizarCompra2;
    private javax.swing.JButton FinalizarCompra3;
    private javax.swing.JButton FinalizarCompra4;
    private javax.swing.JButton FinalizarCompra5;
    private javax.swing.JButton FinalizarCompra6;
    private javax.swing.JButton FinalizarCompra7;
    private javax.swing.JButton FinalizarCompra8;
    private javax.swing.JButton FinalizarCompra9;
    private javax.swing.JPanel InformacaoSistema;
    private javax.swing.JPanel Opercao;
    private javax.swing.JPanel PainelValorPago;
    private javax.swing.JTextField SubTotal;
    private javax.swing.JPanel ValorTotalApagar;
    private javax.swing.JPanel ValortotalCompra;
    private org.jdesktop.swingx.JXImagePanel imagePanel;
    private org.jdesktop.swingx.JXImagePanel imagePanelLogo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
