package Visualiza.login;


import Controle.CampoDigitado.ControleGeral;
import Controle.Geral.ValidacaoSenhaLogin;
import Visualiza.PrincipalMenu;

public class LoginInicial extends javax.swing.JFrame {

  
    public LoginInicial() {
       
        initComponents();
        setLocationRelativeTo(null);
        UsuarioSenha.setDocument(new ControleGeral(10,"[aA-zZ]"));
        UsuarioLogin.setDocument(new ControleGeral(10,"[0-9]"));
        PrincipalMenu principalMenu = new PrincipalMenu(UsuarioLogin.getText());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LebalUsuario = new javax.swing.JLabel();
        LabelSenha = new javax.swing.JLabel();
        EntraSistema = new javax.swing.JButton();
        UsuarioLogin = new javax.swing.JTextField();
        UsuarioSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuário");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LebalUsuario.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        LebalUsuario.setText("Usuário");

        LabelSenha.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        LabelSenha.setText("Senha");

        EntraSistema.setText("entrar");
        EntraSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntraSistemaActionPerformed(evt);
            }
        });
        EntraSistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EntraSistemaKeyPressed(evt);
            }
        });

        UsuarioLogin.setFont(new java.awt.Font("Arial Narrow", 0, 30)); // NOI18N
        UsuarioLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioLoginKeyPressed(evt);
            }
        });

        UsuarioSenha.setFont(new java.awt.Font("Arial Narrow", 0, 30)); // NOI18N
        UsuarioSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioSenhaKeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("@ 2014-2014 Pizzaria. Todos os direitos reservados.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntraSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LebalUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LebalUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSenha)
                    .addComponent(UsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntraSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntraSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntraSistemaActionPerformed

            
boolean CampoVazio = ValidacaoSenhaLogin.CampoVazio(UsuarioLogin.getText(), UsuarioSenha.getText());
        System.out.println(CampoVazio);
        //caso o retorno do banco de dados for verdadeiro
        //fecha o login e abre menuPrincipal
            PrincipalMenu principalMenu = new PrincipalMenu(UsuarioLogin.getText());
      
          principalMenu.setVisible(true);
          dispose();
          
    // TODO add your handling code here:
    }//GEN-LAST:event_EntraSistemaActionPerformed

    private void UsuarioLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioLoginKeyPressed

          if(evt.getKeyCode() == evt.VK_ENTER){
        UsuarioSenha.requestFocus();
          }
    // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioLoginKeyPressed

    private void UsuarioSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioSenhaKeyPressed
  if(evt.getKeyCode() == evt.VK_ENTER){
    EntraSistema.requestFocus();
  }
    // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioSenhaKeyPressed

    private void EntraSistemaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntraSistemaKeyPressed

          if(evt.getKeyCode() == evt.VK_ENTER){
          PrincipalMenu principalMenu = new PrincipalMenu(UsuarioLogin.getText());
          principalMenu.setVisible(true);
          dispose();
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_EntraSistemaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntraSistema;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LebalUsuario;
    private javax.swing.JTextField UsuarioLogin;
    private javax.swing.JPasswordField UsuarioSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}



